### ISSUE TITLE
Manual install without using composer?

### ISSUE THREAD

**Issue by Jacob-Wilsons** [cloudflare/Cloudflare-Magento#57]
I want to install this plugin manually

1) What is the folder name where I need to upload files?

2) Is this the correct command to enable it?
```
bin/magento module:enable cloudflare-magento
bin/magento setup:upgrade
```

Thanks

**Comment by jwineman** [comment]
Hi @Jacob-Wilsons,

You can try putting the files at `app\code\CloudFlare\Plugin` but I've never tested this so I'm not sure if it will work.  Since we use composer to install our plugin it loads it via the autoloader by namespace from the `vendor/` folder.

Can I ask why you don't want to install via composer?  You can also install via the [Magento Marketplace](https://marketplace.magento.com/cloudflare-cloudflare-magento.html). 

Thanks,
John

**Comment by Jacob-Wilsons** [comment]
Hi, @jwineman 

thanks for reply. I do not use composer because it is not installed in my VPS. I heard people had some issues using composer and I decided not it install it, for this reason I installed all plugins manually.

**Comment by navarr** [comment]
@Jacob-Wilsons I don't think you'll be able to install this plugin without composer as it has additional dependencies.

Composer is just another PHP file.  [Download it](https://getcomposer.org/installer), rename it, and run it using php.

Then you can either install Cloudflare through the instructions listed, or drop it in app/code and then install it's dependency by running `composer require cloudflare/cloudflare-plugin-backend`

**Comment by jwineman** [comment]
@Jacob-Wilsons I would _highly_ suggest you use composer.  Its the defacto package manager for PHP, and used extensively by Magento 2.  You'll save yourself a lot of headache if you use it since thats how Magento 2 also manages dependencies.

**Comment by Jacob-Wilsons** [comment]
I tested and looks like @navarr and @jwineman are right, you can not install this plugin without composer. I ended up adding composer to vps. Thank you!
