### ISSUE TITLE
Cloudflare plugin + Varnish + Redis?

### ISSUE THREAD

**Issue by Jacob-Wilsons** [cloudflare/Cloudflare-Magento#60]
It is more a question than an issue. 

Does anyone has has experience on how this Cloudflare plugin geting along with Varnish and Redis on Magento 2. Thank You!

**Comment by navarr** [comment]
The big benefit of this plugin, I think, is the CF-Tags inclusion - which really only applies if you're using Cloudflare Enterprise - which should allow for FPC at the Edge.

While I don't have any actual usage experience quite yet - it should work pretty fine.  You would use Redis for other caches - where this doesn't matter at all, and this + varnish for FPCs; both of which should work fine since I think they both use the cache events to trigger the inclusion of their special headers for clearing it out.

**Comment by jwineman** [comment]
I can't speak to Redis but we hook into all the same cache events that Varnish does.  You can see the Varnish events here:

https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/CacheInvalidate/etc/events.xml

We built Cloudflare counterparts for each event here:
https://github.com/cloudflare/Cloudflare-Magento/blob/master/etc/events.xml

So every time Varnish purge's something Cloudflare will purge as well assuming you have an enterprise account like @navarr said.
